name: gabrielcorado
description: Full-stack developer
meta_description: "Gabriel Corado, full-stack developer"
gems: [jekyll-paginate]

aboutPage: true

markdown: kramdown
highlighter: rouge

paginate: 20
baseurl: /
domain_name: 'http://gabrielcorado.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://gabrielcorado.github.io/'
author:         'Gabriel Corado'

# Posts permalink
permalink:       :year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
